import h5py
import datetime
import numpy as np
import pandas as pd

import fmr2e


def open_dlc_h5(self, h5key=None):
    """ Open the .h5 file generated by DLC.

    Parameters
    ----------
    h5key : str
        The key to the .h5 file. Default is None.

    """
    
    if h5key is None:
        # read the .hf file when there is no key
        pts = pd.read_hdf(self.dlc_path)
    
    else:
        # read in .h5 file when there is a key set in corral_files.py
        pts = pd.read_hdf(self.dlc_path, key=h5key)
    
    # organize columns
    pts.columns = [' '.join(col[:][1:3]).strip() for col in pts.columns.values]
    
    pts = pts.rename(columns={pts.columns[n]: pts.columns[n].replace(' ', '_') for n in range(len(pts.columns))})
    pt_loc_names = pts.columns.values
    return pts, pt_loc_names


def write_h5(filename, dic):
    """ Write a dictionary to an .h5 file.

    The dictionary can only contain values that are of the
    following types: dict, list, numpy.ndarray, or basic scalar
    types (int, float, str, bytes). The hierarchy of the dictionary
    is preserved in the .h5 file that is written. The keys of
    the dictionary can only be type str (not int).

    Parameters
    ----------
    filename : str
        Path to the .h5 file.
    dic : dict
        Dictionary to be saved.

    Notes
    -----
    Modified from https://codereview.stackexchange.com/a/121308

    """

    with h5py.File(filename, 'w') as h5file:

        recursively_save_dict_contents_to_group(h5file, '/', dic)


def recursively_save_dict_contents_to_group(h5file, path, dic):

    if isinstance(dic,dict):
        iterator = dic.items()

    elif isinstance(dic,list):
        iterator = enumerate(dic)

    else:
        ValueError('Cannot save %s type' % type(dic))

    for key, item in iterator:

        if isinstance(dic,list):
            key = str(key)
            
        if isinstance(item, (np.ndarray, np.int16, np.int64, np.float64,
                             int, float, str, bytes, np.float32, np.int32)):
            
            try:
                h5file[path + key] = item
            
            except TypeError:
                if isinstance(item, np.ndarray) and (item.dtype == object):
                    recursively_save_dict_contents_to_group(h5file, path + key + '/', item.item())

        elif isinstance(item, dict) or isinstance(item, list):
            recursively_save_dict_contents_to_group(h5file, path + key + '/', item)

        elif isinstance(item, datetime.datetime):
             h5file[path + key] = fmr2e.time2str(item)

        else:
            raise ValueError('Cannot save %s type'%type(item))

def recursively_load_dict_contents_from_group(h5file, path):
    
    ans = {}

    for key, item in h5file[path].items():

        if isinstance(item, h5py._hl.dataset.Dataset):
            ans[key] = item[()]

        elif isinstance(item, h5py._hl.group.Group):
            ans[key] = recursively_load_dict_contents_from_group(h5file,
                                                                 path + key + '/')

    return ans

def read_h5(filename, ASLIST=False):
    """ Read an .h5 file in as a dictionary.

    Parameters
    ----------
    filename : str
        Path to the .h5 file.
    ASLIST : bool
        If True, the dictionary will be read in as a list (on the first
        layer). Keys must have been convertable to integers when the file
        was written.

    Notes
    -----
    Modified from https://codereview.stackexchange.com/a/121308

    """
    with h5py.File(filename, 'r') as h5file:
        out = recursively_load_dict_contents_from_group(h5file, '/')
        if ASLIST:
            outl = [None for l in range(len(out.keys()))]
            for key, item in out.items():
                outl[int(key)] = item
            out = outl
        return out